@baseUrl = http://localhost:8000/api/v1

GET {{baseUrl}}/tasks

###

GET {{baseUrl}}/tasks/2

###

POST {{baseUrl}}/tasks
Content-Type: application/json

{
    "name": "Fazer Tapioca"
}

###

POST {{baseUrl}}/tasks/1
Content-Type: application/json

{
    "name": "Fazer Bolo"
}

###

DELETE  {{baseUrl}}/tasks/4

###

DELETE {{baseUrl}}/tasks
